name: haskoin-core
version: 0.13.5
synopsis: Bitcoin & Bitcoin Cash library for Haskell
description: 'Haskoin Core is a complete Bitcoin and Bitcoin Cash library of functions and data types for Haskell developers.'
category: Bitcoin, Finance, Network
author:
  - Philippe Laprade
  - Jean-Pierre Rupp
  - Matthew Wraith
maintainer: jprupp@protonmail.ch
license: PublicDomain
license-file: UNLICENSE
homepage: http://github.com/haskoin/haskoin#readme
git: git://github.com/haskoin/haskoin.git
bug-reports: http://github.com/haskoin/haskoin/issues
extra-source-files:
  - data/*.json
  - README.md
  - CHANGELOG.md
dependencies:
  aeson: ">= 1.4.6.0"
  array: ">= 0.5.4.0"
  base: ">=4.9 && <5"
  base16-bytestring: ">= 0.1.1.6"
  bytestring: ">= 0.10.10.0"
  cereal: ">= 0.5.8.1"
  conduit: ">= 1.3.1.2"
  containers: ">= 0.6.2.1"
  cryptonite: ">= 0.26"
  deepseq: ">= 1.4.4.0"
  entropy: ">= 0.4.1.5"
  hashable: ">= 1.3.0.0"
  memory: ">= 0.15.0"
  mtl: ">= 2.2.2"
  murmur3: ">= 1.0.3"
  network: ">= 3.1.1.1"
  split: ">= 0.2.3.3"
  safe: ">= 0.3.18"
  scientific: ">= 0.3.6.2"
  secp256k1-haskell: ">= 0.2.1"
  string-conversions: ">= 0.4.0.1"
  text: ">= 1.2.4.0"
  time: ">= 1.9.3"
  transformers: ">= 0.5.6.2"
  unordered-containers: ">= 0.2.10.0"
  vector: ">= 0.12.1.2"
library:
  source-dirs: src
  exposed-modules:
    - Haskoin
    - Haskoin.Address
    - Haskoin.Block
    - Haskoin.Constants
    - Haskoin.Crypto
    - Haskoin.Keys
    - Haskoin.Network
    - Haskoin.Script
    - Haskoin.Transaction
    - Haskoin.Util
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover
    dependencies:
      hspec: ">= 2.7.1"
      HUnit: ">= 1.6.0.0"
      QuickCheck: ">= 2.13.2"
