flags: {}
packages:
- 'haskoin-wallet'
- location: '.'
  subdirs:
    - haskoin-core
    - haskoin-node
    - secp256k1-haskell
  extra-dep: true
extra-deps:
- concurrent-extra-0.7.0.10
- daemons-0.2.1
- murmur3-1.0.1
- pbkdf-1.1.1.1
- cereal-0.5.1.0
resolver: lts-4.1
